### ISSUE TITLE
Client forgets about advancement while mining cobble

### ISSUE THREAD

**Issue by wknowleskellett** [BluePsychoRanger/SkyBlock_Collection#16] opened 2024-03-07 22:51 UTC
<img width="1094" alt="image" src="https://github.com/BluePsychoRanger/SkyBlock_Collection/assets/39969985/9302fac3-04c6-4fc8-ac19-7139c1a09baf">

The server is using:
- Standard SkyBlock v1.0.4 (Packaged)
- Sky Void Additions v1.1.4 (Packaged)
- SkyBlock Advancements v1.0.1
The server is also serving the advancements resource pack.

As shown in the image, the client regularly forgets about the `cobble_gen_check` advancement and reloads the datapacks.

**Comment by BluePsychoRanger** [comment] 2024-03-08 00:42
This is caused by the bug linked below. It can be fixed by revoking the advancement immediately, so that's something that @EpyonProjects will implement soon.
https://bugs.mojang.com/browse/MC-196976

**Comment by BluePsychoRanger** [comment] 2024-03-08 16:33
This has been fixed in SkyVoid Advancements v1.0.2

**Closed by BluePsychoRanger** 2024-03-08 16:33 UTC

**Comment by wknowleskellett** [comment] 2024-03-19 14:15
Thanks for the update, and thanks so much for providing this to everybody.
